FROM node:12-alpine

# Create app dir and use it as the working dir
RUN mkdir -p /client
WORKDIR /client

COPY .npmrc /client/.npmrc

COPY package.json /client
COPY package.json /client

RUN npm install

RUN rm -f /client/.npmrc

COPY . /client

RUN npm run start
