FROM node:12-alpine
RUN mkdir -p /srv/client
WORKDIR /srv/client
ENV PATH /srv/client/node_modules/.bin:$PATH
COPY .npmrc /srv/client/.npmrc
COPY package.json /srv/client
RUN npm install
RUN rm -f /srv/client/.npmrc
COPY . /srv/client