# build environment
FROM node:12-alpine 

WORKDIR /client

ENV PATH /client/node_modules/.bin:$PATH

COPY .npmrc /client

COPY package.json /client

RUN npm install
RUN rm -f /client/.npmrc

COPY . /client

RUN npm run build
