FROM node:12-alpine

# Create app dir and use it as the working dir
RUN mkdir -p /srv/client
WORKDIR /srv/client

ENV PATH /srv/client/node_modules/.bin:$PATH

COPY .npmrc /srv/client/.npmrc

COPY package.json /srv/client

RUN npm install

RUN rm -f /srv/client/.npmrc

COPY . /srv/client

# CMD ["npm","run","start"]