version: '3.3'

services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: "server:1.0.0"
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - '.srv/server:/srv/server'
      - '/srv/client/node_modules'
    networks:
      - net-chat
    command: npm run start

  client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: "client:1.0.0"
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './srv/client:/srv/client'
      - '/srv/client/node_modules'
    links:
      - server
    networks:
      - net-chat

  revproxy:
    build: ./revproxy
    image: "revproxy:1.0.0"
    networks:
      - net-chat
    ports:
      - 3003:3003

networks:
  net-chat: