version: '3'

services:
# Setup server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose: 
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP-SERVER_PORT: ${APP_SERVER_PORT}
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/server/src
    command: npm run start


    # Setup client

  client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment: 
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    expose:
      - ${APP_CLIENT_PORT}
    ports: 
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    links:
      - server
    command: npm run start