version: '3.3'

services:

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server/src:/srv/app-ays-chat-server/src
    command: npm run start


  client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './srv/client:/srv/client'
      - '/srv/client/node_modules'
    links:
      - server