version: '3'

services:
# Setup server
  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP-SERVER_PORT: ${APP_SERVER_PORT}
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app-ays-chat-server/src
    command: npm run start


    # Setup client

  client:
    tty: true
    build: ./client
    environment: 
      - APP_CLIENT_PORT=${APP_CLIENT_PORT}
    expose:
      - ${APP_CLIENT_PORT}
    ports: 
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}
    volumes:
      - ./client/src:/srv/app-ays-chat-client/src
      - ./client/public:/srv/app-ays-chat-client/public
    links:
      - server
    command: npm run start
